#!/usr/bin/env Rscript
# Parity fixtures for kmeans_rust_operator, generated by the R reference
# (stats::kmeans, R 4.3.3 — see parity/README.md). Run from the
# kmeans_rust_operator directory:
#
#   Rscript tests/parity/generate_goldens.R
#
# Everything written here is public data (the operator's own test1 input,
# Fisher's iris) or synthetic, seeded, and reproducible from this script.
# Numeric output uses sprintf("%.17g") — 15 digits is not enough to decide
# bitwise parity (create-rust-operator §6).

dir <- function(...) file.path("tests", "parity", ...)
dir.create(dir(), showWarnings = FALSE, recursive = TRUE)

num <- function(x) paste(sprintf("%.17g", x), collapse = ",")
csv_line <- function(f, ..., header = FALSE) {
  parts <- unlist(list(...), use.names = FALSE)
  cat(paste(parts, collapse = ","), "\n", sep = "", file = f, append = !header)
}

write_matrix <- function(name, mat) {
  f <- dir(paste0(name, "_matrix.csv"))
  csv_line(f, paste0("v", seq_len(ncol(mat))), header = TRUE)
  for (i in seq_len(nrow(mat))) csv_line(f, num(mat[i, ]))
}

write_case <- function(name, mat, centers, iter.max, nstart, seed) {
  set.seed(seed)
  km <- kmeans(mat, centers = centers, iter.max = iter.max, nstart = nstart)
  tag <- sprintf("%s_k%d_i%d_s%d_seed%d", name, centers, iter.max, nstart, seed)

  f <- dir(paste0(tag, "_labels.csv"))
  csv_line(f, "cluster", header = TRUE)
  for (v in km$cluster) csv_line(f, as.integer(v))

  f <- dir(paste0(tag, "_centers.csv"))
  csv_line(f, paste0("c", seq_len(ncol(mat))), header = TRUE)
  for (i in seq_len(nrow(km$centers))) csv_line(f, num(km$centers[i, ]))

  f <- dir(paste0(tag, "_meta.csv"))
  csv_line(f, "iter", "ifault", "tot_withinss",
           paste0("wss", seq_len(length(km$withinss))), header = TRUE)
  csv_line(f, km$iter, km$ifault, sprintf("%.17g", km$tot.withinss),
           num(km$withinss))
}

write_sample_int <- function(cases) {
  f <- dir("sample_int.csv")
  # seed,m,k,idx1..idxk — R's sample.int(m, k) right after set.seed(seed);
  # the port's RRng::sample_int must produce exactly these draws.
  csv_line(f, "seed", "m", "k", "idx", header = TRUE)
  for (cs in cases) {
    set.seed(cs$seed)
    idx <- sample.int(cs$m, cs$k)
    csv_line(f, cs$seed, cs$m, cs$k, paste(idx, collapse = " "))
  }
}

## ---- inputs ---------------------------------------------------------------

# The R operator's own test1 input, projected the way main.R projects it:
# acast(.ci ~ .ri, value.var = "y_values", fun.aggregate = mean).
raw <- read.csv("tests/test1_in.csv")
test1 <- tapply(raw$y_values, list(raw$Observation, raw$Variable), mean)
test1 <- test1[order(as.numeric(sub("obs", "", rownames(test1)))),
               order(as.numeric(sub("var", "", colnames(test1))))]
write_matrix("test1", test1)

# Fisher's iris (public reference data), measurements only.
iris_m <- as.matrix(iris[, 1:4])
write_matrix("iris", iris_m)

# Synthetic, seeded, 300 points x 8 variables: enough points for the
# optimal-transfer stage to actually iterate.
set.seed(1)
synth <- matrix(rnorm(300 * 8, mean = rep(seq(0, 14, 2), each = 300 / 5)), ncol = 8)
write_matrix("synthetic", synth)

# Duplicated rows: exercises the R wrapper's `any(duplicated(centers))`
# re-sampling from the distinct rows.
set.seed(2)
base_m <- matrix(rnorm(120 * 5), ncol = 5)
dup_m <- base_m[sample.int(120, 200, replace = TRUE), ]
write_matrix("duplicates", dup_m)

## ---- cases ----------------------------------------------------------------

write_case("test1",     test1,    2, 10, 1, 42)  # the operator's own golden
write_case("test1",     test1,    3, 10, 1, 7)
write_case("iris",      iris_m,   3, 10, 1, 42)
write_case("iris",      iris_m,   8,  1, 1, 1)   # iter.max exceeded (ifault 2)
write_case("iris",      iris_m,   5, 10, 3, 9)   # nstart > 1
write_case("synthetic", synth,    6, 10, 1, 2024)
write_case("synthetic", synth,   12, 10, 1, 3)
write_case("synthetic", synth,    4, 10, 4, 11)
write_case("duplicates", dup_m,   4, 10, 1, 5)   # duplicate initial centres
write_case("duplicates", dup_m,   4, 10, 3, 5)

## ---- raw RNG draws --------------------------------------------------------

write_sample_int(list(
  list(seed = 42,  m = 10,  k = 2),
  list(seed = 42,  m = 100, k = 10),
  list(seed = 7,   m = 150, k = 3),
  list(seed = 1,   m = 300, k = 8),
  list(seed = 5,   m = 200, k = 4),
  list(seed = 2024, m = 300, k = 6),
  list(seed = 3,   m = 9,   k = 9),   # k == m
  list(seed = 11,  m = 1,   k = 1)    # degenerate
))

cat("fixtures written to", dir(), "\n")
