//! Parity against the R reference (`tests/parity/`, generated by
//! `generate_goldens.R` with R 4.3.3's `stats::kmeans`).
//!
//! The claim is bitwise: on identical seeded inputs the port must produce
//! the same cluster labels, the same centres to the last bit (`%.17g`
//! round-trips a double exactly), the same within-cluster sums, and the
//! same iteration count — including R's `sample.int`-drawn initial centres
//! and its `nstart` selection. Files whose name carries the case's
//! parameters (`<name>_k<k>_i<iter>_s<nstart>_seed<seed>`) are enumerated
//! from the directory, so adding a case in the generator adds it here.

use std::fs;
use std::path::Path;

use kmeans_rust_operator::kmeans::kmeans;
use kmeans_rust_operator::rng::RRng;

/// Distance between two doubles in units of the last place of the larger.
fn ulp_diff(a: f64, b: f64) -> f64 {
    if a == b {
        return 0.0;
    }
    (a - b).abs() / f64::max(f64::abs(a), f64::abs(b)) / f64::EPSILON
}

/// Minimal CSV: header line, then comma-separated fields.
fn read_csv(path: &Path) -> Vec<Vec<String>> {
    let text = fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    text.lines()
        .filter(|l| !l.trim().is_empty())
        .map(|l| l.split(',').map(|s| s.trim().to_string()).collect())
        .collect()
}

fn read_matrix(path: &Path) -> (usize, usize, Vec<f64>) {
    let rows = read_csv(path);
    let p = rows[0].len();
    let data: Vec<f64> = rows[1..]
        .iter()
        .flat_map(|r| r.iter().map(|v| v.parse::<f64>().unwrap()))
        .collect();
    assert_eq!(data.len() % p, 0, "{}: ragged matrix", path.display());
    (data.len() / p, p, data)
}

struct Meta {
    iter: usize,
    ifault: i32,
    tot_withinss: f64,
    wss: Vec<f64>,
}

fn read_meta(path: &Path) -> Meta {
    let rows = read_csv(path);
    assert_eq!(rows.len(), 2, "{}", path.display());
    let header = &rows[0];
    let values = &rows[1];
    let mut iter = 0;
    let mut ifault = 0;
    let mut tot = 0.0;
    let mut wss = Vec::new();
    for (i, name) in header.iter().enumerate() {
        match name.as_str() {
            "iter" => iter = values[i].parse().unwrap(),
            "ifault" => ifault = values[i].parse().unwrap(),
            "tot_withinss" => tot = values[i].parse().unwrap(),
            _ if name.starts_with("wss") => wss.push(values[i].parse().unwrap()),
            other => panic!("unexpected meta column {other}"),
        }
    }
    Meta {
        iter,
        ifault,
        tot_withinss: tot,
        wss,
    }
}

/// `<name>_k<k>_i<iter>_s<nstart>_seed<seed>`.
fn parse_tag(tag: &str) -> (usize, usize, usize, u32) {
    let get = |prefix: &str| -> u32 {
        tag.split('_')
            .filter_map(|f| f.strip_prefix(prefix))
            .find_map(|rest| rest.parse().ok())
            .unwrap_or_else(|| panic!("{tag}: missing {prefix}"))
    };
    (
        get("k") as usize,
        get("i") as usize,
        get("s") as usize,
        get("seed"),
    )
}

#[test]
fn parity_with_the_r_reference_on_every_fixture() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/parity");
    let mut checked = 0;
    for entry in fs::read_dir(&dir).unwrap() {
        let path = entry.unwrap().path();
        let name = path.file_name().unwrap().to_str().unwrap().to_string();
        let Some(tag) = name.strip_suffix("_labels.csv") else {
            continue;
        };
        let (k, iter_max, nstart, seed) = parse_tag(tag);
        // The matrix file is named after the case's input (`test1`, `iris`,
        // …), which is everything before the first `_k` in the tag.
        let input_name = tag.split_once("_k").map(|(n, _)| n).unwrap_or(tag);
        let ((m, p), x) = {
            let (m, p, data) = read_matrix(&dir.join(format!("{input_name}_matrix.csv")));
            ((m, p), data)
        };
        let labels: Vec<i64> = read_csv(&dir.join(format!("{tag}_labels.csv")))[1..]
            .iter()
            .map(|r| r[0].parse().unwrap())
            .collect();
        let centers_rows = read_csv(&dir.join(format!("{tag}_centers.csv")));
        let want_centers: Vec<f64> = centers_rows[1..]
            .iter()
            .flat_map(|r| r.iter().map(|v| v.parse::<f64>().unwrap()))
            .collect();
        let meta = read_meta(&dir.join(format!("{tag}_meta.csv")));

        let mut rng = RRng::set_seed(seed);
        let fit = kmeans(&x, m, p, k, iter_max, nstart, &mut rng)
            .unwrap_or_else(|e| panic!("{tag}: {e}"));

        assert_eq!(
            fit.cluster,
            labels.iter().map(|v| (v - 1) as usize).collect::<Vec<_>>(),
            "{tag}: cluster labels differ"
        );
        assert_eq!(fit.centers.len(), want_centers.len(), "{tag}: centre shape");
        for (i, (a, b)) in fit.centers.iter().zip(&want_centers).enumerate() {
            assert_eq!(
                a.to_bits(),
                b.to_bits(),
                "{tag}: centre {i} differs bitwise: {a} vs {b}"
            );
        }
        for (i, (a, b)) in fit.wss.iter().zip(&meta.wss).enumerate() {
            assert_eq!(a.to_bits(), b.to_bits(), "{tag}: wss {i} differs bitwise");
        }
        // R's sum() accumulates in long double and rounds once, so its
        // tot.withinss can sit one ulp away from an f64 accumulation of the
        // same (bitwise-equal) per-cluster wss. The operator publishes labels
        // only; the nstart selection compares per-cluster wss that are
        // bitwise, so see kmeans.rs for why this cannot flip a selection.
        assert!(
            ulp_diff(fit.tot_withinss, meta.tot_withinss) <= 1.0,
            "{tag}: tot.withinss differs by more than 1 ulp: {} vs {}",
            fit.tot_withinss,
            meta.tot_withinss
        );
        assert_eq!(fit.iter, meta.iter, "{tag}: iteration count differs");
        assert_eq!(fit.ifault, meta.ifault, "{tag}: ifault differs");
        match meta.ifault {
            0 => assert!(fit.warnings.is_empty(), "{tag}: unexpected warnings"),
            2 => assert!(
                fit.warnings
                    .iter()
                    .any(|w| w.starts_with("did not converge")),
                "{tag}: missing non-convergence warning"
            ),
            other => panic!("{tag}: unexpected fixture ifault {other}"),
        }
        checked += 1;
    }
    assert!(
        checked >= 10,
        "parity fixtures missing — run tests/parity/generate_goldens.R (found {checked})"
    );
}

/// The raw RNG draws: `sample.int(m, k)` right after `set.seed(seed)`.
#[test]
fn the_rng_reproduces_r_sample_int_draw_for_draw() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/parity/sample_int.csv");
    for row in read_csv(&path).iter().skip(1) {
        let seed: u32 = row[0].parse().unwrap();
        let m: usize = row[1].parse().unwrap();
        let k: usize = row[2].parse().unwrap();
        let want: Vec<usize> = row[3].split(' ').map(|v| v.parse().unwrap()).collect();
        let mut rng = RRng::set_seed(seed);
        let got = rng.sample_int(m, k);
        assert_eq!(
            got,
            want.iter().map(|v| v - 1).collect::<Vec<_>>(),
            "seed={seed} sample.int({m}, {k})"
        );
    }
}
