//! kmeans_rust_operator — Rust port of `tercen/kmeans_operator` (R
//! `stats::kmeans`, Hartigan–Wong, over the projected crosstab).
//!
//! The crosstab contract: rows are variables, columns are observations, y is
//! the measurement. The operator streams the cell table in bounded chunks and
//! gathers it into the matrix the R operator builds with
//! `acast(.ci ~ .ri, mean)` — one point per observation column — clusters it,
//! and returns one cluster label per observation column on `.ci`.
//!
//! Parity with the R operator is bitwise on identical seeded inputs: the
//! Hartigan–Wong engine is a statement-for-statement transliteration of R's
//! Fortran (`kmns.rs`), the initial centres come from R's own RNG
//! (`rng.rs`) through the same `sample.int` draws, and the R wrapper's init
//! quirks (the duplicate-row re-sample, the `nstart` selection) are ported
//! (`kmeans.rs`). Goldens: `tests/parity/`, generated by the R reference.
pub mod chunked;
pub mod context;
pub mod input;
pub mod kmeans;
pub mod kmns;
pub mod output;
pub mod progress;
pub mod props;
pub mod rng;
pub mod tson;
pub mod upload;

use std::sync::Arc;
use std::time::Instant;

use anyhow::{Context, Result, anyhow};
use tercen_rs::context::ContextBase;
use tercen_rs::{DevContext, TercenClient};

use progress::Reporter;
use rng::RRng;

pub fn init_tracing() {
    let filter = tracing_subscriber::EnvFilter::try_from_default_env()
        .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info"));
    let _ = tracing_subscriber::fmt().with_env_filter(filter).try_init();
}

pub fn require_env(name: &str) -> Result<String> {
    std::env::var(name).map_err(|_| anyhow!("{name} is not set"))
}

/// Production entry point (`--taskId`).
pub async fn run(task_id: &str) -> Result<()> {
    tracing::info!("kmeans_rust_operator starting (task_id={task_id})");
    let client = build_client().await?;
    // Deliberately not `ProductionContext::from_task_id`: see context.rs.
    let ctx = context::from_task_id(client, task_id).await?;
    execute(
        &ctx,
        Mode::Production {
            task_id: task_id.to_string(),
        },
    )
    .await
}

/// Dev entry point (`WORKFLOW_ID` / `STEP_ID`).
pub async fn run_dev(workflow_id: &str, step_id: &str) -> Result<()> {
    tracing::info!("kmeans_rust_operator starting in dev mode ({workflow_id} / {step_id})");
    let client = build_client().await?;
    let ctx = DevContext::from_workflow_step(client, workflow_id, step_id)
        .await
        .map_err(|e| anyhow!("load workflow {workflow_id} / step {step_id}: {e}"))?;
    execute(
        &ctx,
        Mode::Dev {
            workflow_id: workflow_id.to_string(),
            step_id: step_id.to_string(),
        },
    )
    .await
}

enum Mode {
    Production {
        task_id: String,
    },
    Dev {
        workflow_id: String,
        step_id: String,
    },
}

async fn build_client() -> Result<Arc<TercenClient>> {
    let client = TercenClient::from_env()
        .await
        .map_err(|e| anyhow!("connect to Tercen: {e}"))?;
    tracing::info!("connected to Tercen");
    Ok(Arc::new(client))
}

async fn execute(ctx: &ContextBase, mode: Mode) -> Result<()> {
    let t_start = Instant::now();
    tracing::info!(
        workflow = ctx.workflow_id(),
        step = ctx.step_id(),
        namespace = ctx.namespace(),
        "context loaded"
    );
    let rep = match &mode {
        Mode::Production { task_id } => Reporter::spawn(Arc::clone(ctx.client()), task_id.clone()),
        Mode::Dev { .. } => Reporter::silent(),
    };
    let s = props::settings_from_ctx(ctx)?;
    tracing::info!(?s, "properties");

    // The whole matrix must be gathered: a kmeans centre is a mean over every
    // point and every point is measured against every centre (see
    // memory_model.json for the booking). The gather streams the cell table
    // chunk by chunk — it is never held whole (input.rs).
    rep.at(progress::READ.0, "Reading the crosstab");
    let mat = input::gather_matrix(ctx).await?;
    let m = mat.n_points();
    let p = mat.n_vars();
    tracing::info!(points = m, variables = p, "crosstab gathered");

    rep.at(progress::WRITE.0, "Clustering");
    let mut rng = make_rng(s.seed);
    let t = Instant::now();
    let fit = kmeans::kmeans(&mat.data, m, p, s.centers, s.iter_max, s.nstart, &mut rng)?;
    for w in &fit.warnings {
        rep.info(format!("kmeans: {w}"));
    }
    tracing::info!(
        k = s.centers,
        nstart = s.nstart,
        iter = fit.iter,
        secs = format!("{:.1}", t.elapsed().as_secs_f64()),
        "clustering done"
    );
    rep.info(format!(
        "kmeans: {} cluster(s) over {m} observations, {} iteration(s), total within-SS {:.6e}",
        s.centers, fit.iter, fit.tot_withinss
    ));

    let work_root =
        std::env::temp_dir().join(format!("kmeans_op_{}_{}", ctx.workflow_id(), ctx.step_id()));
    std::fs::create_dir_all(&work_root)
        .with_context(|| format!("create {}", work_root.display()))?;
    let result_path = work_root.join("result.tson");
    {
        let f = std::fs::File::create(&result_path)
            .with_context(|| format!("create {}", result_path.display()))?;
        let mut w = tson::TsonWriter::new(std::io::BufWriter::with_capacity(1 << 20, f))?;
        output::write_result(&mut w, &uuid_like(ctx), &fit.cluster, ctx.namespace())?;
    }

    rep.at(progress::UPLOAD.0, "Uploading the result");
    match mode {
        Mode::Production { task_id } => {
            upload::save_production(ctx, &task_id, &result_path, &rep).await?
        }
        Mode::Dev {
            workflow_id,
            step_id,
        } => {
            let saved = upload::save_dev(ctx, &workflow_id, &step_id, &result_path).await?;
            tracing::info!(
                task_id = saved.task_id,
                file_id = saved.file_id,
                "dev result saved"
            );
        }
    }
    let _ = std::fs::remove_dir_all(&work_root);
    rep.at(100, "Done");
    tracing::info!(
        total_secs = format!("{:.1}", t_start.elapsed().as_secs_f64()),
        peak_rss_kb = peak_rss_kb().unwrap_or(0),
        "done"
    );
    Ok(())
}

/// `seed` property: `Some(s)` is R `set.seed(s)`; `None` is R
/// `set.seed(NULL)`, which seeds from the clock and is unreproducible — the
/// port uses OS entropy there, and a seeded run is the only parity path.
fn make_rng(seed: Option<i32>) -> RRng {
    match seed {
        Some(s) => RRng::set_seed(s as u32),
        None => {
            use std::hash::{BuildHasher, Hasher};
            let mut h = std::collections::hash_map::RandomState::new().build_hasher();
            h.write_u64(
                std::time::SystemTime::now()
                    .duration_since(std::time::UNIX_EPOCH)
                    .map(|d| d.as_nanos() as u64)
                    .unwrap_or(0),
            );
            RRng::set_seed(h.finish() as u32)
        }
    }
}

/// A stable per-run table name (`save_table` uses a uuid; the value is never read back).
fn uuid_like(ctx: &ContextBase) -> String {
    format!("{}_{}", ctx.step_id(), ctx.qt_hash())
}

fn peak_rss_kb() -> Option<u64> {
    let s = std::fs::read_to_string("/proc/self/status").ok()?;
    s.lines()
        .find(|l| l.starts_with("VmHWM:"))?
        .split_whitespace()
        .nth(1)?
        .parse()
        .ok()
}
